### ISSUE TITLE
你好 ，想请教rabbitmq的延迟队列如何实现

### ISSUE THREAD

**Issue by Android-BRUCE** [vector4wang/spring-boot-quick#10]
大佬，小白想请教rabbitmq的延迟队列如何实现，你的rabbitmq模块中貌似还没加入呢

**Comment by vector4wang** [comment]
好的，我尽快加上去~~~

**Comment by vector4wang** [comment]
@Android-BRUCE 
https://github.com/vector4wang/spring-boot-quick/tree/master/quick-rabbitmq
这个延迟队列是针对msg而不是针对queue，不知道能不能帮到你

**Comment by Android-BRUCE** [comment]
Duplicate of # @vector4wang 灰常感谢。嗯，请问是不是一开始消息是投递到了延迟队列上并且是设置了ttl以及死信后处理的process_exchange和routing-key，当消息过期后由process_exchange根据routing-key，再次投递到正常需要消费队列上嘛

**Comment by vector4wang** [comment]
@Android-BRUCE  完全正确~~~
