### ISSUE TITLE
那个csdn导出的怎么使用啊

### ISSUE THREAD

**Issue by neghao** [vector4wang/spring-boot-quick#11]

**Comment by vector4wang** [comment]
@neghao `CSDN2mdService.convertAllBlogByUserName(String username)`就是导出整个博客的方法，很久之前的代码了，不保证现在能顺利运行

**Comment by vector4wang** [comment]
@neghao 我把这个模块抽出来了，https://github.com/vector4wang/blog-export-quick  写了相关说明

启动项目之后，在浏览器输入网址`http://localhost:8002/tool/html2md`

[![ui](https://i.loli.net/2018/06/12/5b1f895d4f4fb.png)](https://i.loli.net/2018/06/12/5b1f895d4f4fb.png)

你可以再链接框内输入CSDN的文章链接如

"https://blog.csdn.net/qqhjqs/article/details/79101846",

你也可以将html源码输入“源代码”框中

然后点击转换，即可得到对应的MD格式的文件~~~

`CSDN2mdService.convertAllBlogByUserName(String username)` 

这个方法可以把该用户下的所有博客导出来(直接在main方法里调用该方法就行了)

>补充：html转md 这个方法，到目前为止没有哪个人敢说自己能将html百分之百转换为md，因为html样式千奇百怪，所以针对一些不复杂的html，此方法还是有效的

**Comment by Ruffianjiang** [comment]
@neghao  正好我也看到了这块，这两天修改了作者的代码，根据用户名抓取 「csdn」 、「博客园」的全部文章，适合做一次性博客迁移 「markdown」 的工作，参考地址 「https://github.com/Ruffianjiang/dawn-example/tree/master/html2md」
