### ISSUE TITLE
Spark远程调用

### ISSUE THREAD

**Issue by jaaaar** [vector4wang/spring-boot-quick#13]
嗨，在博客站看到你的springboot和spark示例，
请问如何实现以下需求呢?

在windows环境开发，linux虚拟机装spark, 如何在windows的springboot开发项目中，在一个junit test中远程调用linux中的spark执行任务呢?

**Comment by vector4wang** [comment]
这个应该不行吧？

要了解spark支不支持测试用例，如果支持的话应该就可以！

spark也就一年之前搞过皮毛，没有太深入的了解。。。。不好意思了哥们

**Comment by jaaaar** [comment]
谢谢
