### ISSUE TITLE
Consumer和Logkafka 没有可用数据

### ISSUE THREAD

**Issue by zhangyinyuan** [vector4wang/spring-boot-quick#14]
按照楼主的文档,已经可以正常发送消息和消费消息. 
但是在 kafka-manager上看不到以下数据
![image](https://user-images.githubusercontent.com/17852036/61684647-b35f5580-ad4c-11e9-987f-9ec2c8a94ee9.png)

![image](https://user-images.githubusercontent.com/17852036/61684668-c70abc00-ad4c-11e9-86b6-0aeb1b7f5802.png)

请问您这边是否也遇到同样的问题?

**Comment by vector4wang** [comment]
我晚点时候看一下， 我这边只发送和接受消息，并没有去关注manager，

**Comment by vector4wang** [comment]
kafka manager的仓库中有相同的问题 [#496](https://github.com/yahoo/kafka-manager/issues/496)

**Comment by vector4wang** [comment]
我发现现在用的镜像最后一次更新是一年前，考虑到版本迭代，我找了个更新时间最近的镜像，执行脚本如下
```bash
docker run -d \
  	--link zookeeper:zookeeper \
        -p 9000:9000  \
        -e ZK_HOSTS="zookeeper:2181" \
        hlebalbau/kafka-manager:stable \
       -Dpidfile.path=/dev/null
```
然后manager中的consumer就能正常显示了
![image](https://user-images.githubusercontent.com/9328963/61756343-1bb24380-adee-11e9-9d23-e6d915627ec1.png)

你把之前的manager删掉，用这个试试
