### ISSUE TITLE
逼死强迫症

### ISSUE THREAD

**Issue by chenxiujin** [vector4wang/spring-boot-quick#17]
![image](https://user-images.githubusercontent.com/39232016/81271098-3eac9c00-907e-11ea-88eb-c3e63e3a3d11.png)

spring-boot-quick/quick-activemq2/src/main/java/com/active2/config/ActiveMQConfig.java
#56 57行缩进两次tap  （手动狗头-_-!）

**Comment by vector4wang** [comment]
厉害了我的哥，来个PR我处理下😂🤣
