### ISSUE TITLE
为什么放弃thymeleaf呢

### ISSUE THREAD

**Issue by rogerfanrui** [vector4wang/spring-boot-quick#2]
是因为性能原因吗？

**Comment by vector4wang** [comment]
不是的！其实我本来打算用jsp的，毕竟jsp开发自己做过大半年较熟练，但是不知道是什么原因，自己配置jsp的时候老是不成功，然后考虑使用th或freemarker，至于为什么选择了freemarker个人偏好，没有任何性能之类的原因。
后来一阿里的哥们说我配置jsp不成功的问题可能是idea的bug，最后最后就选择使用了freemarker。强调一下，我是喜爱JSP的！！！

**Comment by rogerfanrui** [comment]
font{
        line-height: 1.5;
    }


    
哈哈 好的。 我们团队刚刚从jsp/freemarker 切换至thymeleaf ，因为大家伙是远程开发，前端的一些小调整总是要技术的介入成本太高



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2017年07月20日 18:19，wangxc<notifications@github.com> 写道： 


不是的！其实我本来打算用jsp的，毕竟jsp开发自己做过大半年较熟练，但是不知道是什么原因，自己配置jsp的时候老是不成功，然后考虑使用th或freemarker，至于为什么选择了freemarker个人偏好，没有任何性能之类的原因。
后来一阿里的哥们说我配置jsp不成功的问题可能是idea的bug，最后最后就选择使用了freemarker。强调一下，我是喜爱JSP的！！！

**Comment by vector4wang** [comment]
“远程开发”是指团队人员都不在一起是嘛~~~，那项目进展有那么顺利么

**Comment by rogerfanrui** [comment]
font{
        line-height: 1.5;
    }


    
不那么顺畅，沟通成本还是很高，还是觉得跟团队每个人的技术栈相关。如果每个任务都需要协调产品、设计、前端、开发、测试 ， 那就歇菜了呢。



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    

    在2017年07月21日 09:36，wangxc<notifications@github.com> 写道： 


“远程开发”是指团队人员都不在一起是嘛~~~，那项目进展有那么顺利么

**Comment by vector4wang** [comment]
那这个项目不是你的主业吧，空闲时间接的活吧

**Comment by rogerfanrui** [comment]
font{
        line-height: 1.5;
    }


    
哈哈，差不多，不过是一个长期性的项目 



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2017年07月21日 10:45，wangxc<notifications@github.com> 写道： 


那这个项目不是你的主业吧，空闲时间接的活吧

**Comment by vector4wang** [comment]
挺好，充分利用空闲的时间赚钱，真不错~

**Comment by rogerfanrui** [comment]
font{
        line-height: 1.5;
    }


    
还是买不起房  娶不上媳妇 



    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #3593db;
            cursor: pointer;
        }
    

                
                    发自网易邮箱大师                



    在2017年07月21日 10:49，wangxc<notifications@github.com> 写道： 


挺好，充分利用空闲的时间赚钱，真不错~

**Comment by vector4wang** [comment]
说的我竟无言以对~
