### ISSUE TITLE
多个modules挂上去，能统一启动么。

### ISSUE THREAD

**Issue by wurangbo** [vector4wang/spring-boot-quick#3]

**Comment by vector4wang** [comment]
这个需要**CI**(持续集成)，如jenkins，如果是工具包之类的话可以搭建个maven私服引用

**Comment by wurangbo** [comment]
我的意思是每一个module都有自己的业务，如rest接口，想动态加载业务功能。

**Comment by vector4wang** [comment]
> 想动态加载业务功能

这个是什么意思

**Comment by wurangbo** [comment]
就是将打包好jar包（包含rest接口），系统能够将其自动加载，将接口发布。

**Comment by vector4wang** [comment]
@wurangbo  这个需要CI 或者 使用maven的热部署的插件

**Comment by wurangbo** [comment]
devtools？还是其他

**Comment by vector4wang** [comment]
@wurangbo devtools 可以的，但是我推荐用jenkins做CI，支持多节点，最近我也打算要搞这一块，因为我这有四个环境，每次写好的时候，都是手动去部署，自己准备尝试jenkins的多节点部署

**Comment by wurangbo** [comment]
我关注的是如何加载目录下的jar文件，然后将对象实例化到servelet容器中。

**Comment by wurangbo** [comment]
hi，我想问一下，我将多个jar模块聚合为一个war包启动，但是jar中包含的rest接口始终没有起来，是有那些需要配置的吗。

**Comment by vector4wang** [comment]
@wurangbo 不好意思，我没见过这种做法，可能是我孤陋寡闻了

我的都是每个服务（你指的jar）独立发布
