### ISSUE TITLE
build的时候报错了

### ISSUE THREAD

**Issue by gaoneng1989** [vector4wang/spring-boot-quick#4]
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.3.2.RELEASE:repackage (default) on project quick-spark: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:1.3.2.RELEASE:repackage failed: Unable to find a single main class from the following candidates [spark.Application, spark.textmatch.SimHash, com.spark.scala.LinearRegression, com.spark.textmatch.TextMatch, spark.test.java.EmailFilter, spark.test.java.Test, spark.test.java.Word2VecTest] -> [Help 1]

**Comment by vector4wang** [comment]
**quick-spark**

好像是这个模块出现的问题，问题就是你需要配置spark相关的环境。你在网上找一下安装spark环境的资料，然后试一下 ^_^

---
